### PR TITLE
Add Hebrew

### PR DESCRIPTION
**Pull request by TheGrits**
https://scratch.mit.edu/users/The_Grits/#comments-26074028

Add Hebrew, credit to ItsDaBunnyYT for the translation!

### CODE REVIEW

**Comment by TheGrits** [comment]
@LiFaytheGoblin Do you happen to know anyone that could double check Hebrew for us?

**Comment by Ascor8522** [comment]
@TheGrits Easy task...
Just search "Hebrew" in the Scratch's search engine and let's see who are the owners of the first projects...

Then, select the active users and those who really speak Hebrew.

Here is a "small" list:

https://scratch.mit.edu/users/koorkevani/ (last activity: 1 week ago + 14 years old)
https://scratch.mit.edu/users/darthaider123/ (last activity: 1 weeks ago)
https://scratch.mit.edu/users/talmir/ (last activity: 2 weeks ago)

https://scratch.mit.edu/users/oded2015/ (last activity: 3 weeks ago)
https://scratch.mit.edu/users/ichack1000/ (last activity: 3 weeks ago)
https://scratch.mit.edu/users/sburak/  (last activity: 1 month ago + teacher)
https://scratch.mit.edu/users/guyalf1/ (last activity: 1 month ago)
https://scratch.mit.edu/users/erodin10/ (last activity: 1 month ago)

https://scratch.mit.edu/users/OM1000/ (last activity: 2 month ago)

https://scratch.mit.edu/users/scimonster/ (last activity: 3 months ago)
https://scratch.mit.edu/users/avivstru/ (last activity: 3 months ago)

https://scratch.mit.edu/users/xchui/ (last activity: 4 months ago)

**Comment by TheGrits** [comment]
@Smrman While that is a clever way of finding someone who speaks Hebrew, I would prefer someone that @LiFaytheGoblin knows so that we know for sure that the person actually speaks Hebrew.

Thanks anyway!

**Comment by Ascor8522** [comment]
> **TheGrits** wrote: _I would prefer someone that @LiFaytheGoblin knows_

Sure!

**Comment by LiFaytheGoblin** [comment]
@TheGrits 

Scimonster, the former Scratch moderator, knows Hebrew! Maybe we could ask them!

**Comment by TheGrits** [comment]
@Scimonster 

I left a comment on your Scratch profile, but it looks like you are inactive there. 

Would you be willing to double check that this translation matches the description of the current SDS?
We're building a site with translations of the SDS description so as to make it more accessible to non-English Scratchers. If you could help by checking this translation, it would be greatly appreciated.

Many thanks!

**Comment by Scimonster** [comment]
First of all, this is a great idea.

As for the translation itself, it's not so great. If i have time, I'll fork and edit the translation.

**Comment by TheGrits** [comment]
@Scimonster Thanks, that would be fantastic!

**Comment by Scimonster** [comment]
I'm not sure you should really credit them with this translation. I plugged the text into Google Translate and it gave me 95% of what is here. I'm using that as a base to modify into something that looks written by a human. My Hebrew isn't native-level, but i think it's OK.

**Comment by Scimonster** [comment]
Made a pull request; this one can be closed now.

**Comment by TheGrits** [comment]
@Scimonster Great, thanks!

**Pull request closed without merging**
